export const WORLD_STUDIO_ERROR_CODES = {
  ACCESS_DENIED: 'WORLD_ACCESS_DENIED',
  STRUCTURED_OUTPUT_INVALID: 'WORLD_STUDIO_STRUCTURED_OUTPUT_INVALID',
  PUBLISH_ROLLBACK: 'WORLD_STUDIO_PUBLISH_ROLLBACK',
  CONFLICT: 'WORLD_STUDIO_CONFLICT',
  PARSE_JOB_FAILED: 'WORLD_STUDIO_PARSE_JOB_FAILED',
  PHASE1_ALL_CHUNKS_FAILED: 'WORLD_STUDIO_PHASE1_ALL_CHUNKS_FAILED',
  PHASE1_NO_CHARACTER_CANDIDATES: 'WORLD_STUDIO_PHASE1_NO_CHARACTER_CANDIDATES',
  PHASE1_QUALITY_GATE_BLOCKED: 'WORLD_STUDIO_PHASE1_QUALITY_GATE_BLOCKED',
  COARSE_JSON_PARSE_FAILED: 'WORLD_STUDIO_COARSE_JSON_PARSE_FAILED',
  FINE_JSON_PARSE_FAILED: 'WORLD_STUDIO_FINE_JSON_PARSE_FAILED',
  MODEL_ROUTE_INVALID: 'WORLD_STUDIO_MODEL_ROUTE_INVALID',
  SYNTHESIZE_BLOCKED_BY_EVENT_GRAPH: 'WORLD_STUDIO_SYNTHESIZE_BLOCKED_BY_EVENT_GRAPH',
  EVENT_GRAPH_INVALID: 'WORLD_STUDIO_EVENT_GRAPH_INVALID',
  EVENT_EVIDENCE_REQUIRED: 'WORLD_STUDIO_EVENT_EVIDENCE_REQUIRED',
  MAINTENANCE_CONFLICT: 'WORLD_STUDIO_MAINTENANCE_CONFLICT',
} as const;

export type WorldStudioErrorCode =
  typeof WORLD_STUDIO_ERROR_CODES[keyof typeof WORLD_STUDIO_ERROR_CODES];
