export const WORLD_STUDIO_CONTRACT_VERSION = '2026-03-26';

export {
  WORLD_STUDIO_MOD_ID,
  WORLD_STUDIO_TAB_ID,
  WORLD_STUDIO_NAV_SLOT,
  WORLD_STUDIO_ROUTE_SLOT,
  WORLD_STUDIO_DATA_API_ACCESS_ME,
  WORLD_STUDIO_DATA_API_LANDING_RESOLVE,
  WORLD_STUDIO_DATA_API_DRAFT_CREATE,
  WORLD_STUDIO_DATA_API_DRAFT_GET,
  WORLD_STUDIO_DATA_API_DRAFT_UPDATE,
  WORLD_STUDIO_DATA_API_DRAFT_PUBLISH,
  WORLD_STUDIO_DATA_API_STATE_GET,
  WORLD_STUDIO_DATA_API_STATE_COMMIT,
  WORLD_STUDIO_DATA_API_WORLD_BY_ID_GET,
  WORLD_STUDIO_DATA_API_WORLDVIEW_BY_ID_GET,
  WORLD_STUDIO_DATA_API_HISTORY_LIST,
  WORLD_STUDIO_DATA_API_HISTORY_APPEND,
  WORLD_STUDIO_DATA_API_LOREBOOKS_LIST,
  WORLD_STUDIO_DATA_API_LOREBOOKS_BATCH_UPSERT,
  WORLD_STUDIO_DATA_API_LOREBOOKS_DELETE,
  WORLD_STUDIO_DATA_API_BINDINGS_LIST,
  WORLD_STUDIO_DATA_API_BINDINGS_BATCH_UPSERT,
  WORLD_STUDIO_DATA_API_BINDINGS_DELETE,
  WORLD_STUDIO_DATA_API_DRAFTS_LIST,
  WORLD_STUDIO_DATA_API_WORLDS_MINE,
  WORLD_STUDIO_DATA_API_SCENES_LIST,
  WORLD_STUDIO_DATA_API_NARRATIVE_CONTEXTS_LIST,
  WORLD_STUDIO_DATA_API_CREATOR_AGENTS_LIST,
  WORLD_STUDIO_DATA_API_CREATOR_AGENTS_GET,
  WORLD_STUDIO_DATA_API_CREATOR_AGENTS_CREATE,
  WORLD_STUDIO_DATA_API_CREATOR_AGENTS_UPDATE,
  WORLD_STUDIO_DATA_API_CREATOR_AGENTS_BATCH_CREATE,
  WORLD_STUDIO_STATE_TARGET_PATH,
  WORLD_STUDIO_STATE_SCHEMA_ID,
  WORLD_STUDIO_STATE_SCHEMA_VERSION,
  WORLD_STUDIO_HISTORY_EVENT_TYPE,
  WORLD_STUDIO_HISTORY_SCHEMA_ID,
  WORLD_STUDIO_HISTORY_SCHEMA_VERSION,
} from './contracts/constants.js';

export {
  WORLD_STUDIO_ERROR_CODES,
  type WorldStudioErrorCode,
} from './contracts/errors.js';

export {
  WORLD_STUDIO_CAPABILITIES,
} from './contracts/capabilities.js';

export type * from './contracts/types/workspace.js';
export type * from './contracts/types/generation.js';
