import {
  AUDIO_BOOK_CAPABILITIES,
  AUDIO_BOOK_MOD_ID,
  AUDIO_BOOK_NAV_SLOT,
  AUDIO_BOOK_ROUTE_SLOT,
} from './contracts.js';

export const AUDIO_BOOK_MANIFEST = {
  id: AUDIO_BOOK_MOD_ID,
  name: 'Audio Book',
  version: '0.1.0',
  description: 'Multi-character AI voice narration and audiobook generation',
  author: { name: 'Nimi', url: 'https://nimi.xyz' },
  license: 'MIT',
  iconAsset: './assets/icon.svg',
  entry: './dist/mods/audio-book/index.js',
  styles: ['./dist/mods/audio-book/index.css'],
  hash: 'default-audio-book',
  nimi: {
    minVersion: '1.0.0',
    maxVersion: '2.x',
  },
  capabilities: [...AUDIO_BOOK_CAPABILITIES],
  dependencies: [],
  hooks: {
    uiExtensions: [
      {
        slot: AUDIO_BOOK_NAV_SLOT,
        componentRef: 'audio-book:navigation-item',
      },
      {
        slot: AUDIO_BOOK_ROUTE_SLOT,
        componentRef: 'audio-book:route-page',
      },
    ],
  },
  ai: {
    consume: ['chat', 'tts'],
    profiles: [
      {
        id: 'audio-book-default',
        title: 'Default narration stack',
        description: 'Balanced audiobook stack with Qwen2.5 chat and Qwen3 TTS 1.7B.',
        recommended: true,
        consumeCapabilities: ['chat', 'tts'],
        entries: [
          {
            entryId: 'audio-book/chat-qwen2.5-7b',
            kind: 'model',
            capability: 'chat',
            modelId: 'qwen2.5-7b-instruct',
            repo: 'Qwen/Qwen2.5-7B-Instruct-GGUF',
            engine: 'openai-compatible',
            title: 'Qwen2.5 7B Instruct (analysis)',
            required: true,
            preferred: true,
          },
          {
            entryId: 'audio-book/tts-qwen3-1.7b',
            kind: 'service',
            capability: 'tts',
            serviceId: 'qwen-tts-python',
            modelId: 'Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign',
            repo: 'Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign',
            engine: 'qwen-tts-python',
            title: 'Qwen3 TTS 1.7B (recommended)',
            required: true,
            preferred: true,
          },
        ],
      },
      {
        id: 'audio-book-compact',
        title: 'Compact narration stack',
        description: 'Smaller audiobook stack with Qwen2.5 chat and Qwen3 TTS 0.6B.',
        recommended: false,
        consumeCapabilities: ['chat', 'tts'],
        entries: [
          {
            entryId: 'audio-book/chat-qwen2.5-7b',
            kind: 'model',
            capability: 'chat',
            modelId: 'qwen2.5-7b-instruct',
            repo: 'Qwen/Qwen2.5-7B-Instruct-GGUF',
            engine: 'openai-compatible',
            title: 'Qwen2.5 7B Instruct (analysis)',
            required: true,
            preferred: true,
          },
          {
            entryId: 'audio-book/tts-qwen3-0.6b',
            kind: 'service',
            capability: 'tts',
            serviceId: 'qwen-tts-python',
            modelId: 'Qwen/Qwen3-TTS-12Hz-0.6B-VoiceDesign',
            repo: 'Qwen/Qwen3-TTS-12Hz-0.6B-VoiceDesign',
            engine: 'qwen-tts-python',
            title: 'Qwen3 TTS 0.6B',
            required: true,
            preferred: true,
          },
        ],
      },
    ],
  },
} as const;
