import type { RuntimeRouteBinding, RuntimeRouteOptionsSnapshot, RuntimeRouteSource } from '@nimiplatform/sdk/mod/runtime-route';
import type {
  LocalChatInspectSettings,
  LocalChatPromptTrace,
  LocalChatTurnAudit,
} from '../../state/index.js';
import type { HealthStatus, LocalChatResolvedMediaRoute } from '../../types.js';
import type { ChatRouteSnapshot } from '../../hooks/runtime-route/types.js';

export type RuntimeStatusSidebarProps = {
  healthStatus: HealthStatus;
  checkingHealth: boolean;
  chatRouteOptions: RuntimeRouteOptionsSnapshot | null;
  imageRouteOptions: RuntimeRouteOptionsSnapshot | null;
  videoRouteOptions: RuntimeRouteOptionsSnapshot | null;
  imageResolvedRoute?: LocalChatResolvedMediaRoute | null;
  videoResolvedRoute?: LocalChatResolvedMediaRoute | null;
  routeSnapshot?: ChatRouteSnapshot | null;
  routeBinding?: RuntimeRouteBinding | null;
  speechVoices: Array<{ id: string; providerId?: string; name: string }>;
  selectedSpeechProviderId?: string;
  selectedVoiceId: string;
  ttsRouteSource: 'auto' | 'local' | 'cloud';
  sttRouteSource: 'auto' | 'local' | 'cloud';
  imageRouteSource: 'auto' | 'local' | 'cloud';
  videoRouteSource: 'auto' | 'local' | 'cloud';
  localTtsRouteAvailable: boolean;
  localSttRouteAvailable: boolean;
  enableVoice: boolean;
  autoBoundSource: RuntimeRouteSource | 'mixed' | 'unknown';
  autoBoundModel: string;
  chatRouteReady: boolean;
  chatCapabilityMatched: boolean;
  dependencyCapabilities: Array<{
    capability: 'chat' | 'tts' | 'stt' | 'image' | 'video' | 'text.generate' | 'audio.synthesize' | 'audio.transcribe';
    matched: boolean;
    required: boolean;
    resolved: boolean;
  }>;
  dependencyStatus: 'ready' | 'missing' | 'degraded' | 'unknown';
  dependencyReasonCode?: string;
  dependencyUpdatedAt?: string;
  isMediaRuntimeSidebarLoading?: boolean;
  isImageRouteProbeLoading?: boolean;
  isVideoRouteProbeLoading?: boolean;
  dependencyRepairActions: Array<{
    actionId: string;
    label: string;
    reasonCode: string;
    dependencyId?: string;
    capability?: string;
  }>;
  latestPromptTrace: LocalChatPromptTrace | null;
  latestTurnAudit: LocalChatTurnAudit | null;
  onRouteSourceChange: (source: RuntimeRouteSource) => void;
  onRouteConnectorChange: (connectorId: string) => void;
  onRouteModelChange: (model: string) => void;
  onClearRouteBinding?: () => void;
  onVoiceIdChange: (voiceId: string) => void;
  ttsConnectorId: string;
  ttsModel: string;
  sttConnectorId: string;
  sttModel: string;
  imageConnectorId: string;
  imageModel: string;
  videoConnectorId: string;
  videoModel: string;
  ttsConnectors: Array<{ id: string; label: string; models: string[]; modelCapabilities?: Record<string, string[]> }>;
  sttConnectors: Array<{ id: string; label: string; models: string[]; modelCapabilities?: Record<string, string[]> }>;
  imageConnectors: Array<{ id: string; label: string; models: string[]; modelCapabilities?: Record<string, string[]> }>;
  videoConnectors: Array<{ id: string; label: string; models: string[]; modelCapabilities?: Record<string, string[]> }>;
  onTtsRouteSourceChange: (source: 'auto' | 'local' | 'cloud') => void;
  onTtsConnectorChange: (connectorId: string) => void;
  onTtsModelChange: (model: string) => void;
  onSttRouteSourceChange: (source: 'auto' | 'local' | 'cloud') => void;
  onSttConnectorChange: (connectorId: string) => void;
  onSttModelChange: (model: string) => void;
  onImageRouteSourceChange: (source: 'auto' | 'local' | 'cloud') => void;
  onImageConnectorChange: (connectorId: string) => void;
  onImageModelChange: (model: string) => void;
  onVideoRouteSourceChange: (source: 'auto' | 'local' | 'cloud') => void;
  onVideoConnectorChange: (connectorId: string) => void;
  onVideoModelChange: (model: string) => void;
  onHealthCheck: () => void;
  onOpenRuntimeSetup: () => void;
  inspectSettings: LocalChatInspectSettings;
  sidebarVisible?: boolean;
  onRefreshMediaDependencies?: () => void;
  onSidebarBootstrap?: () => void;
  onOpenChatPanel?: () => void;
  onOpenVoicePanel?: () => void;
  onOpenMediaPanel?: () => void;
};
