import type { RuntimeRouteBinding, RuntimeRouteOptionsSnapshot, RuntimeRouteSource } from '@nimiplatform/sdk/mod/runtime-route';
import type { LocalChatBooleanSettingKey, LocalChatDefaultSettings, LocalChatPromptTrace, LocalChatTurnAudit } from '../../state/index.js';
import type { HealthStatus } from '../../types.js';

export type RuntimeStatusSidebarProps = {
  healthStatus: HealthStatus;
  checkingHealth: boolean;
  chatRouteOptions: RuntimeRouteOptionsSnapshot | null;
  routeOverride: RuntimeRouteBinding | null;
  speechProviders: Array<{ id: string; name: string; status: 'available' | 'unavailable' }>;
  speechVoices: Array<{ id: string; providerId: string; name: string }>;
  selectedSpeechProviderId: string;
  selectedVoiceId: string;
  ttsRouteSource: 'auto' | 'local-runtime' | 'token-api';
  sttRouteSource: 'auto' | 'local-runtime' | 'token-api';
  localTtsRouteAvailable: boolean;
  localSttRouteAvailable: boolean;
  autoBoundSource: RuntimeRouteSource | 'mixed' | 'unknown';
  autoBoundModel: string;
  chatCapabilityMatched: boolean;
  dependencyCapabilities: Array<{
    capability: 'chat' | 'tts' | 'stt';
    matched: boolean;
    required: boolean;
  }>;
  dependencyStatus: 'ready' | 'missing' | 'degraded' | 'unknown';
  dependencyReasonCode?: string;
  dependencyUpdatedAt?: string;
  dependencyRepairActions: Array<{
    actionId: string;
    label: string;
    reasonCode: string;
    dependencyId?: string;
    capability?: string;
  }>;
  latestPromptTrace: LocalChatPromptTrace | null;
  latestTurnAudit: LocalChatTurnAudit | null;
  onRouteSourceChange: (source: RuntimeRouteSource) => void;
  onRouteConnectorChange: (connectorId: string) => void;
  onRouteModelChange: (model: string) => void;
  onClearRouteOverride: () => void;
  onSpeechProviderChange: (providerId: string) => void;
  onVoiceIdChange: (voiceId: string) => void;
  ttsConnectorId: string;
  ttsModel: string;
  sttConnectorId: string;
  sttModel: string;
  connectors: Array<{ id: string; label: string; models: string[] }>;
  onTtsRouteSourceChange: (source: 'auto' | 'local-runtime' | 'token-api') => void;
  onTtsConnectorChange: (connectorId: string) => void;
  onTtsModelChange: (model: string) => void;
  onSttRouteSourceChange: (source: 'auto' | 'local-runtime' | 'token-api') => void;
  onSttConnectorChange: (connectorId: string) => void;
  onSttModelChange: (model: string) => void;
  onHealthCheck: () => void;
  onOpenRuntimeSetup: () => void;
  defaultSettings: LocalChatDefaultSettings;
  onDefaultSettingChange: (key: LocalChatBooleanSettingKey, value: boolean) => void;
  onDefaultVoiceNameChange: (value: string) => void;
};
