import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const testDir = path.dirname(fileURLToPath(import.meta.url));
const modDir = path.resolve(testDir, '..');

function readModFile(relativePath) {
  return readFileSync(path.join(modDir, relativePath), 'utf8');
}

test('world-studio manifest declares css entry for UI runtime shell', () => {
  const manifest = readModFile('mod.manifest.yaml');
  assert.match(manifest, /^styles:\s*$/m);
  assert.match(manifest, /^\s*-\s+\.\/dist\/mods\/world-studio\/index\.css\s*$/m);
});

test('world-studio page root keeps the required mod root marker', () => {
  const pageSource = readModFile('src/world-studio-page.tsx');
  assert.match(pageSource, /data-nimi-mod-root="world-studio"/);
  assert.match(pageSource, /className="flex h-full min-h-0 min-w-0 flex-1 overflow-hidden bg-\[#eef7f5\]"/);
});

test('world-studio route uses immersive shell mode and a standard in-flow shell root', () => {
  const indexSource = readModFile('src/index.ts');
  const shellSource = readModFile('src/ui/world-studio-shell.tsx');
  assert.match(indexSource, /shellMode:\s*'immersive'/);
  assert.match(shellSource, /data-ui-version="v5"/);
  assert.match(shellSource, /workflowSidebar: React\.ReactNode/);
  assert.match(shellSource, /shell\.settingsDrawer/);
  assert.match(shellSource, /absolute inset-y-0 right-0 z-30/);
  assert.match(shellSource, /className="ui-sync-root relative isolate flex h-full min-h-0 min-w-0 w-full flex-1 overflow-hidden bg-\[#eef7f5\]"/);
  assert.doesNotMatch(shellSource, /fixed inset-x-0 bottom-0/);
  assert.doesNotMatch(shellSource, /viewportTop/);
});

test('create workbench implements import and review subviews with sticky action bar', () => {
  const workbenchSource = readModFile('src/ui/create/create-workbench.tsx');
  const stageNavSource = readModFile('src/ui/create/create-stage-nav.tsx');
  const builderSource = readModFile('src/controllers/world-studio-screen-model-builder.ts');
  assert.match(workbenchSource, /main\.importSubview === 'PREPARE'/);
  assert.match(workbenchSource, /main\.importSubview === 'RUNNING'/);
  assert.match(workbenchSource, /main\.reviewSubview === 'PUBLISH_REVIEW'/);
  assert.match(workbenchSource, /renderSourceInputPanel/);
  assert.match(workbenchSource, /<StickyActionBar>/);
  assert.match(stageNavSource, /disabled=\{disabled\}/);
  assert.match(builderSource, /buildCreateStageAccess/);
  assert.match(builderSource, /resolveRequestedCreateStage/);
});

test('maintain workbench removes mutations from the primary editor workflow', () => {
  const maintainSource = readModFile('src/ui/maintain/maintain-workbench.tsx');
  const workflowDrawerSource = readModFile('src/ui/workflow-drawer.tsx');
  const domainNavSource = readModFile('src/ui/maintain/domain-nav.tsx');
  const sectionNavSource = readModFile('src/ui/maintain/section-nav.tsx');
  const agentsPanelSource = readModFile('src/ui/maintain/agents-panel.tsx');
  const assetsPanelSource = readModFile('src/ui/maintain/assets-panel.tsx');
  const releasesPanelSource = readModFile('src/ui/maintain/releases-panel.tsx');
  const worldBasePanelSource = readModFile('src/ui/maintain/world-base-panel.tsx');
  const worldviewPanelSource = readModFile('src/ui/maintain/worldview-panel.tsx');
  const eventsPanelSource = readModFile('src/ui/maintain/events-panel.tsx');
  const draftEditorPanelSource = readModFile('src/ui/create/draft-editor-panel.tsx');
  const eventWorkbenchSource = readModFile('src/ui/shared/event-graph-workbench.tsx');
  const localeZh = readModFile('src/locales/zh.json');
  const workspaceTypes = readModFile('src/contracts/types/workspace.ts');
  const builderSource = readModFile('src/controllers/world-studio-screen-model-builder.ts');
  const normalizeSource = readModFile('src/state/workspace/normalize.ts');
  const runPhase2Source = readModFile('src/hooks/actions/create/run-phase2.ts');
  assert.doesNotMatch(maintainSource, /section === 'MUTATIONS'/);
  assert.match(maintainSource, /SectionNav/);
  assert.match(maintainSource, /saveLocalWorkspace\(\)/);
  assert.match(maintainSource, /syncWorkspaceToRemote\(\)/);
  assert.match(maintainSource, /reloadFromRemote\(\)/);
  assert.match(workflowDrawerSource, /DomainNav/);
  assert.match(workflowDrawerSource, /statusSummary\.title/);
  assert.match(workflowDrawerSource, /workflow\.domainNavDescription/);
  assert.match(domainNavSource, /worldStudioMessage/);
  assert.match(sectionNavSource, /sectionNav\.worldEvents/);
  assert.match(sectionNavSource, /sectionNav\.worldAssets/);
  assert.match(sectionNavSource, /sectionNav\.agentAssets/);
  assert.doesNotMatch(sectionNavSource, /AGENTS:\s*\[[\s\S]*value:\s*'EDITOR'/);
  assert.match(maintainSource, /maintain\.saveLocal/);
  assert.match(maintainSource, /maintain\.syncToRemote/);
  assert.match(maintainSource, /maintain\.reloadFromRemote/);
  assert.match(maintainSource, /maintain\.forceSyncToRemote/);
  assert.match(maintainSource, /SectionContextCard/);
  assert.match(maintainSource, /maintain\.section\.baseTitle/);
  assert.match(maintainSource, /maintain\.localWorkspaceStatusLabel/);
  assert.match(maintainSource, /maintain\.remoteSyncStatusLabel/);
  assert.doesNotMatch(maintainSource, /deleteFirstLorebook/);
  assert.match(assetsPanelSource, /assets\.world\.generatedTitle/);
  assert.match(assetsPanelSource, /assets\.inspect\.open/);
  assert.match(assetsPanelSource, /assets\.world\.missingTitle/);
  assert.match(assetsPanelSource, /assets\.agent\.missingTitle/);
  assert.match(assetsPanelSource, /assets\.agent\.generatedTitle/);
  assert.match(releasesPanelSource, /releases\.drafts\.title/);
  assert.match(releasesPanelSource, /releases\.inspect\.open/);
  assert.match(releasesPanelSource, /releases\.history\.title/);
  assert.match(releasesPanelSource, /releases\.publish\.maintainState/);
  assert.match(releasesPanelSource, /releases\.history\.summary\.total/);
  assert.match(eventsPanelSource, /EventGraphWorkbench/);
  assert.match(draftEditorPanelSource, /EventGraphWorkbench/);
  assert.match(eventWorkbenchSource, /resolveEventWorkbenchSelection/);
  assert.match(eventWorkbenchSource, /eventGraphMaintenance\.openFocus/);
  assert.match(eventWorkbenchSource, /eventGraphMaintenance\.backToInspect/);
  assert.match(eventWorkbenchSource, /eventGraphMaintenance\.backToOverview/);
  assert.match(eventWorkbenchSource, /eventGraphEditor\.summaryLabel/);
  assert.match(eventWorkbenchSource, /eventGraphEditor\.selectedDepsHealthy/);
  assert.match(eventWorkbenchSource, /eventGraphEditor\.selectedMissingEvidence/);
  assert.match(eventWorkbenchSource, /eventGraphEditor\.parentEventMissing/);
  assert.doesNotMatch(eventWorkbenchSource, /worldview\.drawer\.openFocus/);
  assert.doesNotMatch(eventWorkbenchSource, /worldview\.focus\.backToInspect/);
  assert.match(draftEditorPanelSource, /WorldviewPanel/);
  assert.match(draftEditorPanelSource, /LorebooksPanel/);
  assert.match(draftEditorPanelSource, /onWorldviewPatchChange/);
  assert.match(draftEditorPanelSource, /onLorebooksChange/);
  assert.match(worldBasePanelSource, /world\.tagline/);
  assert.match(worldBasePanelSource, /world\.motto/);
  assert.match(worldBasePanelSource, /world\.overview/);
  assert.match(worldBasePanelSource, /world\.contentRating/);
  assert.match(worldBasePanelSource, /clockConfig/);
  assert.match(worldBasePanelSource, /WorldBaseDetailsDisclosure/);
  assert.match(worldBasePanelSource, /WorldBaseReadonlyCode/);
  assert.doesNotMatch(worldBasePanelSource, /next\.clockConfig\s*=/);
  assert.match(worldviewPanelSource, /worldview\.mode\.overview/);
  assert.match(worldviewPanelSource, /worldview\.drawer\.label/);
  assert.match(worldviewPanelSource, /worldview\.focus\.label/);
  assert.match(worldviewPanelSource, /worldview\.modules\.\$\{moduleDefinition\.key\}\.title/);
  assert.match(worldviewPanelSource, /worldview\.modules\.\$\{moduleDefinition\.key\}\.description/);
  assert.match(readModFile('src/ui/maintain/lorebooks-panel.tsx'), /shared\.focusEdit/);
  assert.match(readModFile('src/ui/maintain/lorebooks-panel.tsx'), /lorebooks\.focusTitle/);
  assert.match(agentsPanelSource, /maintain\.saveAgentMetadata/);
  assert.match(agentsPanelSource, /maintain\.createMissingDraftAgents/);
  assert.match(agentsPanelSource, /shared\.inspect/);
  assert.match(agentsPanelSource, /AgentInspectDrawer/);
  assert.match(agentsPanelSource, /type AgentsMode = 'overview' \| 'focus'/);
  assert.match(agentsPanelSource, /setMode\('focus'\)/);
  assert.match(agentsPanelSource, /agents\.registry\.focusSummary/);
  assert.match(agentsPanelSource, /agents\.registry\.pendingHint/);
  assert.match(agentsPanelSource, /activeWorldId/);
  assert.match(agentsPanelSource, /importance/);
  assert.match(agentsPanelSource, /liveState/);
  assert.match(agentsPanelSource, /stats/);
  assert.match(agentsPanelSource, /agents\.registry\.summaryCards\.remoteAgents/);
  assert.match(agentsPanelSource, /agents\.editor\.truthSection/);
  assert.match(agentsPanelSource, /Object\.keys\(draftCacheRef\.current\)\.length > 0/);
  assert.match(agentsPanelSource, /onDirtyChangeRef/);
  assert.doesNotMatch(releasesPanelSource, /New Draft/);
  assert.doesNotMatch(releasesPanelSource, /Open Publish Flow/);
  assert.match(builderSource, /unsavedChangesByPanel\[section\] === dirty/);
  assert.match(localeZh, /"agentRegistry": "角色总览"/);
  assert.match(localeZh, /"domainNavTitle": "维护域"/);
  assert.match(localeZh, /"clockConfig": "时钟配置"/);
  assert.match(localeZh, /"identityTitle": "世界身份卡"/);
  assert.match(localeZh, /"generatedCover": "已生成封面"/);
  assert.match(localeZh, /"maintainState": "维护状态：\{\{value\}\}"/);
  assert.match(localeZh, /"saveLocal": "保存本地"/);
  assert.match(localeZh, /"syncToRemote": "同步到远端"/);
  assert.match(localeZh, /"reloadFromRemote": "从远端重载"/);
  assert.match(localeZh, /"focusEdit": "专注编辑"/);
  assert.match(localeZh, /"label": "当前分区说明"/);
  assert.match(workspaceTypes, /activeDomain: WorldStudioMaintainDomain/);
  assert.match(workspaceTypes, /activeSection: WorldStudioMaintainSection/);
  assert.match(workspaceTypes, /selectedAgentId: string/);
  assert.match(workspaceTypes, /WorldStudioWorldSection = 'BASE' \| 'WORLDVIEW' \| 'WORLD_EVENTS' \| 'LOREBOOKS'/);
  assert.match(readModFile('src/hooks/actions/create/draft-publish.ts'), /activeDomain: 'WORLD'/);
  assert.match(readModFile('src/hooks/actions/create/draft-publish.ts'), /activeSection: 'BASE'/);
  assert.doesNotMatch(readModFile('src/ui/create/phase2-panel.tsx'), /currentTimeNode/);
  assert.doesNotMatch(readModFile('src/controllers/actions/workspace.ts'), /currentNode/);
  assert.doesNotMatch(normalizeSource, /worldPatch\.timeFlowRatio/);
  assert.doesNotMatch(runPhase2Source, /timeFlowRatio/);
});
