export const WORLD_STUDIO_CONTRACT_VERSION = '2026-02-20';

export {
  WORLD_STUDIO_MOD_ID,
  WORLD_STUDIO_TAB_ID,
  WORLD_STUDIO_NAV_SLOT,
  WORLD_STUDIO_ROUTE_SLOT,
  WORLD_STUDIO_DATA_API_ACCESS_ME,
  WORLD_STUDIO_DATA_API_LANDING_RESOLVE,
  WORLD_STUDIO_DATA_API_DRAFT_CREATE,
  WORLD_STUDIO_DATA_API_DRAFT_GET,
  WORLD_STUDIO_DATA_API_DRAFT_UPDATE,
  WORLD_STUDIO_DATA_API_DRAFT_PUBLISH,
  WORLD_STUDIO_DATA_API_MAINTENANCE_GET,
  WORLD_STUDIO_DATA_API_MAINTENANCE_UPDATE,
  WORLD_STUDIO_DATA_API_EVENTS_LIST,
  WORLD_STUDIO_DATA_API_EVENTS_BATCH_UPSERT,
  WORLD_STUDIO_DATA_API_EVENTS_DELETE,
  WORLD_STUDIO_DATA_API_LOREBOOKS_LIST,
  WORLD_STUDIO_DATA_API_LOREBOOKS_BATCH_UPSERT,
  WORLD_STUDIO_DATA_API_LOREBOOKS_DELETE,
  WORLD_STUDIO_DATA_API_DRAFTS_LIST,
  WORLD_STUDIO_DATA_API_WORLDS_MINE,
  WORLD_STUDIO_DATA_API_MUTATIONS_LIST,
  WORLD_STUDIO_DATA_API_CREATOR_AGENTS_LIST,
  WORLD_STUDIO_DATA_API_CREATOR_AGENTS_CREATE,
  WORLD_STUDIO_DATA_API_CREATOR_AGENTS_BATCH_CREATE,
  WORLD_STUDIO_DATA_API_RUNTIME_ROUTE_OPTIONS,
} from './contracts/constants.js';

export {
  WORLD_STUDIO_ERROR_CODES,
  type WorldStudioErrorCode,
} from './contracts/errors.js';

export {
  WORLD_STUDIO_CAPABILITIES,
  WORLD_STUDIO_PERMISSIONS,
} from './contracts/capabilities.js';

export type * from './contracts/types/workspace.js';
export type * from './contracts/types/generation.js';
