import {
  DAILY_OUTFIT_DATA_API_INSIGHTS_QUERY,
  DAILY_OUTFIT_DATA_API_OUTFITS_FAVORITES,
  DAILY_OUTFIT_DATA_API_OUTFITS_GET,
  DAILY_OUTFIT_DATA_API_OUTFITS_LIST,
  DAILY_OUTFIT_DATA_API_PROFILE_READ,
  DAILY_OUTFIT_DATA_API_PROFILE_WRITE,
  DAILY_OUTFIT_DATA_API_WARDROBE_CREATE,
  DAILY_OUTFIT_DATA_API_WARDROBE_GET,
  DAILY_OUTFIT_DATA_API_WARDROBE_LIST,
  DAILY_OUTFIT_DATA_API_WARDROBE_RETIRE,
  DAILY_OUTFIT_DATA_API_WARDROBE_UPDATE,
  DAILY_OUTFIT_DATA_API_WEARLOG_CREATE,
  DAILY_OUTFIT_DATA_API_WEARLOG_LIST,
  DAILY_OUTFIT_MOD_ID,
  DAILY_OUTFIT_NAV_SLOT,
  DAILY_OUTFIT_PERMISSIONS,
  DAILY_OUTFIT_ROUTE_SLOT,
} from './contracts.js';

export const DAILY_OUTFIT_MANIFEST = {
  id: DAILY_OUTFIT_MOD_ID,
  name: 'Daily Outfit',
  version: '1.0.0',
  description: 'Local-first wardrobe planning and outfit history workspace.',
  icon: 'daily-outfit',
  author: { name: 'Nimi', url: 'https://nimi.xyz' },
  license: 'MIT',
  entry: './dist/mods/daily-outfit/index.js',
  hash: 'default-daily-outfit',
  nimi: {
    minVersion: '1.0.0',
    maxVersion: '2.x',
  },
  capabilities: [...DAILY_OUTFIT_PERMISSIONS],
  dependencies: [],
  hooks: {
    dataApis: [
      { name: DAILY_OUTFIT_DATA_API_WARDROBE_LIST, description: 'List wardrobe garments.' },
      { name: DAILY_OUTFIT_DATA_API_WARDROBE_GET, description: 'Read garment detail.' },
      { name: DAILY_OUTFIT_DATA_API_WARDROBE_CREATE, description: 'Create a wardrobe garment.' },
      { name: DAILY_OUTFIT_DATA_API_WARDROBE_UPDATE, description: 'Update garment metadata.' },
      { name: DAILY_OUTFIT_DATA_API_WARDROBE_RETIRE, description: 'Retire a garment without deleting history.' },
      { name: DAILY_OUTFIT_DATA_API_OUTFITS_LIST, description: 'List generated or curated outfits.' },
      { name: DAILY_OUTFIT_DATA_API_OUTFITS_GET, description: 'Read outfit detail.' },
      { name: DAILY_OUTFIT_DATA_API_OUTFITS_FAVORITES, description: 'List favorite outfits.' },
      { name: DAILY_OUTFIT_DATA_API_PROFILE_READ, description: 'Read the user outfit profile.' },
      { name: DAILY_OUTFIT_DATA_API_PROFILE_WRITE, description: 'Write the user outfit profile.' },
      { name: DAILY_OUTFIT_DATA_API_INSIGHTS_QUERY, description: 'Query closet insights.' },
      { name: DAILY_OUTFIT_DATA_API_WEARLOG_LIST, description: 'List wear logs.' },
      { name: DAILY_OUTFIT_DATA_API_WEARLOG_CREATE, description: 'Create a wear log entry.' },
    ],
    uiExtensions: [
      { slot: DAILY_OUTFIT_NAV_SLOT, componentRef: 'daily-outfit:navigation-item' },
      { slot: DAILY_OUTFIT_ROUTE_SLOT, componentRef: 'daily-outfit:route-page' },
    ],
  },
  ai: {
    consume: ['chat', 'image'],
    dependencies: {
      required: [],
      optional: [],
    },
  },
} as const;
