import type { WorldStudioWorkspaceSnapshot } from '../../contracts.js';
import { createEmptyFinalDraftAccumulator } from '../../engine/final-draft-accumulator.js';
import { syncSnapshot } from './normalize.js';

const DEFAULT_SNAPSHOT: WorldStudioWorkspaceSnapshot = {
  panel: {
    searchText: '',
    selectedWorldId: '',
    selectedDraftId: '',
    activeDomain: 'WORLD',
    activeSection: 'BASE',
    selectedAgentId: '',
  },
  createStep: 'SOURCE',
  sourceText: '',
  sourceRef: '',
  worldPatch: {},
  worldviewPatch: {},
  ruleTruthDraft: {
    worldRules: [],
    agentRules: [],
  },
  eventsDraft: {
    primary: [],
    secondary: [],
  },
  lorebooksDraft: [],
  futureEventsText: '[]',
  selectedStartTimeId: '',
  selectedCharacters: [],
  parseJob: {
    phase: 'idle',
    chunkTotal: 0,
    chunkProcessed: 0,
    chunkCompleted: 0,
    chunkFailed: 0,
    progress: 0,
    etaSeconds: null,
    startedAt: null,
    updatedAt: null,
  },
  knowledgeGraph: {
    worldSetting: '',
    timeline: [],
    locations: [],
    characters: [],
    events: {
      primary: [],
      secondary: [],
    },
    characterRelations: [],
    futureHistoricalEvents: [],
    narrativeArc: null,
    characterProfiles: [],
    characterAliasMap: {},
  },
  finalDraftAccumulator: createEmptyFinalDraftAccumulator(),
  phase1Artifact: null,
  draftQuality: {
    worldCutStatus: 'idle',
    enrichStatus: 'idle',
    enrichFailureReason: null,
    weakFieldIssues: [],
    updatedAt: null,
  },
  assets: {
    worldCover: { status: 'idle', imageUrl: null },
    characterPortraits: {},
    locationImages: {},
  },
  agentSync: {
    selectedCharacterIds: [],
    ownershipType: 'WORLD_OWNED',
    targetWorldId: '',
    draftsByCharacter: {},
  },
  eventGraphLayout: {
    selectedEventId: '',
    expandedPrimaryIds: [],
  },
  embeddingIndex: {
    status: 'idle',
    lastBuiltAt: null,
    routeSource: null,
    routeModel: null,
    entries: {},
    errorMessage: null,
  },
  taskState: {
    activeTask: null,
    recentTasks: [],
    expertMode: false,
  },
  editorSnapshotVersion: '',
  unsavedChangesByPanel: {
    base: false,
    worldview: false,
    worldEvents: false,
    lorebooks: false,
    agentRegistry: false,
    agentEditor: false,
    worldAssets: false,
    agentAssets: false,
    releaseDrafts: false,
    releasePublish: false,
    releaseHistory: false,
  },
};

export function cloneDefaultSnapshot(): WorldStudioWorkspaceSnapshot {
  return syncSnapshot({
    ...DEFAULT_SNAPSHOT,
    panel: { ...DEFAULT_SNAPSHOT.panel },
    worldPatch: {},
    worldviewPatch: {},
    ruleTruthDraft: {
      worldRules: [],
      agentRules: [],
    },
    eventsDraft: {
      primary: [],
      secondary: [],
    },
    lorebooksDraft: [],
    selectedCharacters: [],
    parseJob: { ...DEFAULT_SNAPSHOT.parseJob },
    knowledgeGraph: {
      ...DEFAULT_SNAPSHOT.knowledgeGraph,
      timeline: [],
      locations: [],
      characters: [],
      events: {
        primary: [],
        secondary: [],
      },
      characterRelations: [],
      futureHistoricalEvents: [],
      narrativeArc: null,
      characterProfiles: [],
      characterAliasMap: {},
    },
    finalDraftAccumulator: createEmptyFinalDraftAccumulator(),
    phase1Artifact: null,
    draftQuality: {
      ...DEFAULT_SNAPSHOT.draftQuality,
      weakFieldIssues: [],
    },
    assets: {
      worldCover: { ...DEFAULT_SNAPSHOT.assets.worldCover },
      characterPortraits: {},
      locationImages: {},
    },
    agentSync: {
      ...DEFAULT_SNAPSHOT.agentSync,
      selectedCharacterIds: [],
      draftsByCharacter: {},
    },
    eventGraphLayout: { ...DEFAULT_SNAPSHOT.eventGraphLayout, expandedPrimaryIds: [] },
    embeddingIndex: {
      ...DEFAULT_SNAPSHOT.embeddingIndex,
      entries: {},
    },
    taskState: {
      activeTask: null,
      recentTasks: [],
      expertMode: false,
    },
    unsavedChangesByPanel: { ...DEFAULT_SNAPSHOT.unsavedChangesByPanel },
  });
}
