export const VOICE_STUDIO_CONTRACT_VERSION = '2026-03-02';

export const VOICE_STUDIO_MOD_ID = 'world.nimi.voice-studio';
export const VOICE_STUDIO_TAB_ID = 'mod:voice-studio';

export const VOICE_STUDIO_NAV_SLOT = 'ui-extension.app.sidebar.mods';
export const VOICE_STUDIO_ROUTE_SLOT = 'ui-extension.app.content.routes';

export const VOICE_STUDIO_CAPABILITIES = [
  'llm.text.generate',
  'llm.text.stream',
  'llm.speech.voices.list',
  'llm.speech.providers.list',
  'llm.speech.synthesize',
  `ui.register.${VOICE_STUDIO_NAV_SLOT}`,
  `ui.register.${VOICE_STUDIO_ROUTE_SLOT}`,
  'event.publish.vs:synthesis:progress',
  'event.subscribe.vs:synthesis:progress',
] as const;

export const VOICE_STUDIO_PERMISSIONS = [...VOICE_STUDIO_CAPABILITIES] as const;

export const VOICE_STUDIO_ERROR_CODES = {
  IMPORT_EMPTY_TEXT: 'VS_IMPORT_EMPTY_TEXT',
  IMPORT_TOO_LARGE: 'VS_IMPORT_TOO_LARGE',
  IMPORT_NO_CHAPTERS: 'VS_IMPORT_NO_CHAPTERS',
  ANALYSIS_CHAPTER_FAILED: 'VS_ANALYSIS_CHAPTER_FAILED',
  ANALYSIS_INVALID_OUTPUT: 'VS_ANALYSIS_INVALID_OUTPUT',
  ANALYSIS_CANCELLED: 'VS_ANALYSIS_CANCELLED',
  ANALYSIS_ALL_CHAPTERS_FAILED: 'VS_ANALYSIS_ALL_CHAPTERS_FAILED',
  ANALYSIS_NO_DIALOGUE: 'VS_ANALYSIS_NO_DIALOGUE',
  ANALYSIS_CHAPTER_TOO_LONG: 'VS_ANALYSIS_CHAPTER_TOO_LONG',
  CAST_VOICE_UNAVAILABLE: 'VS_CAST_VOICE_UNAVAILABLE',
  CAST_PREVIEW_FAILED: 'VS_CAST_PREVIEW_FAILED',
  CAST_MISSING: 'VS_CAST_MISSING',
  SYNTH_SEGMENT_FAILED: 'VS_SYNTH_SEGMENT_FAILED',
  SYNTH_PROVIDER_UNAVAILABLE: 'VS_SYNTH_PROVIDER_UNAVAILABLE',
  SYNTH_PROVIDER_RATE_LIMITED: 'VS_SYNTH_PROVIDER_RATE_LIMITED',
  SYNTH_TEXT_TOO_LONG: 'VS_SYNTH_TEXT_TOO_LONG',
  STORAGE_QUOTA_EXCEEDED: 'VS_STORAGE_QUOTA_EXCEEDED',
  STORAGE_WRITE_FAILED: 'VS_STORAGE_WRITE_FAILED',
  PLAY_AUDIO_LOAD_FAILED: 'VS_PLAY_AUDIO_LOAD_FAILED',
  PLAY_AUDIO_DECODE_FAILED: 'VS_PLAY_AUDIO_DECODE_FAILED',
} as const;

export type VoiceStudioErrorCode =
  typeof VOICE_STUDIO_ERROR_CODES[keyof typeof VOICE_STUDIO_ERROR_CODES];
